In [7]:
import pandas as pd

data=pd.read_csv(r"C:\Users\user\Downloads\synthetic_dataset.csv")

data.isnull()

      Category  Price  Rating  Stock  Discount
0         True  False   False   True     False
1         True  False   False   True     False
2         True  False    True  False     False
3         True  False   False   True     False
4         True  False    True  False     False
...        ...    ...     ...    ...       ...
4357      True  False   False   True     False
4358     False  False    True  False     False
4359      True  False    True  False     False
4360     False  False   False   True     False
4361      True   True   False   True     False

[4362 rows x 5 columns]

In [11]:
data.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

Mean Imputation

In [16]:
data["Rating"]=data["Rating"].fillna(data["Rating"].mean())

      Category  Price  Rating  Stock  Discount
0         True  False   False   True     False
1         True  False   False   True     False
2         True  False   False  False     False
3         True  False   False   True     False
4         True  False   False  False     False
...        ...    ...     ...    ...       ...
4357      True  False   False   True     False
4358     False  False   False  False     False
4359      True  False   False  False     False
4360     False  False   False   True     False
4361      True   True   False   True     False

[4362 rows x 5 columns]

Meadian Imputation

In [18]:
data["Price"]=data["Price"].fillna(data["Price"].median())
data.isnull()

      Category  Price  Rating  Stock  Discount
0         True  False   False   True     False
1         True  False   False   True     False
2         True  False   False  False     False
3         True  False   False   True     False
4         True  False   False  False     False
...        ...    ...     ...    ...       ...
4357      True  False   False   True     False
4358     False  False   False  False     False
4359      True  False   False  False     False
4360     False  False   False   True     False
4361      True  False   False   True     False

[4362 rows x 5 columns]

Forward Fill

In [21]:
data["Stock"]=data["Stock"].bfill()
data.isnull()

      Category  Price  Rating  Stock  Discount
0         True  False   False  False     False
1         True  False   False  False     False
2         True  False   False  False     False
3         True  False   False  False     False
4         True  False   False  False     False
...        ...    ...     ...    ...       ...
4357      True  False   False  False     False
4358     False  False   False  False     False
4359      True  False   False  False     False
4360     False  False   False  False     False
4361      True  False   False  False     False

[4362 rows x 5 columns]

Encoding Categorical Variable

In [36]:
from sklearn.preprocessing import LabelEncoder

data["Category"]=LabelEncoder().fit_transform(data["Category"])
data.iloc[900:1000]

     Category   Price    Rating         Stock  Discount
900         4  2470.0  1.037354      In Stock      41.0
901         4  1647.0  4.284220      In Stock      27.0
902         2  4351.0  4.134765  Out of Stock       5.0
903         4  9352.0  3.038293  Out of Stock      31.0
904         3  9356.0  3.333491      In Stock      17.0
..        ...     ...       ...           ...       ...
995         4  4917.0  3.038293  Out of Stock      21.0
996         4  8537.0  2.955840  Out of Stock      10.0
997         3  5144.0  3.992800  Out of Stock      27.0
998         4  2806.0  1.074642  Out of Stock      30.0
999         4  9585.0  4.723567      In Stock      24.0

[100 rows x 5 columns]

In [42]:
encoded=pd.get_dummies(data,columns=["Category"])
encoded.iloc[300:600]

,Price,Rating,Stock,Discount,Category_0,Category_1,Category_2,Category_3,Category_4
900,2470.0,1.037354,In Stock,41.0,0,0,0,0,1
901,1647.0,4.284220,In Stock,27.0,0,0,0,0,1
902,4351.0,4.134765,Out of Stock,5.0,0,0,1,0,0
903,9352.0,3.038293,Out of Stock,31.0,0,0,0,0,1
904,9356.0,3.333491,In Stock,17.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
995,4917.0,3.038293,Out of Stock,21.0,0,0,0,0,1
996,8537.0,2.955840,Out of Stock,10.0,0,0,0,0,1
997,5144.0,3.992800,Out of Stock,27.0,0,0,0,1,0
998,2806.0,1.074642,Out of Stock,30.0,0,0,0,0,1
999,9585.0,4.723567,In Stock,24.0,0,0,0,0,1

In [44]:
encoded=pd.get_dummies(data,columns=["Category"],dtype=int)
encoded.iloc[200:500]

,Price,Rating,Stock,Discount,Category_0,Category_1,Category_2,Category_3,Category_4
200,6864.0,2.893483,In Stock,10.0,0,0,0,0,1
201,439.0,2.364554,In Stock,0.0,0,0,1,0,0
202,1425.0,1.803760,In Stock,15.0,1,0,0,0,0
203,1612.0,3.032992,In Stock,16.0,0,0,0,0,1
204,1894.0,2.329488,Out of Stock,NaN,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
495,4905.0,3.038293,Out of Stock,23.0,0,1,0,0,0
496,9922.0,4.966696,In Stock,42.0,0,0,0,0,1
497,2774.0,3.038293,In Stock,0.0,0,0,0,0,1
498,4519.0,4.487539,In Stock,39.0,1,0,0,0,0
499,7967.0,3.038293,In Stock,13.0,0,0,0,0,1